language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

install:
  - npm install --loglevel=error --no-progress

script:
  - npm run build

deploy:
  provider: gcs
  access_key_id: GOOGPVQ4IAYLE52GIVY3
  secret_access_key:
    secure: tH5IWvyzjFjeL/lIIYN/yT2t4FrLm+vIdHYWJZEn05l0csoR6EEQ3Vw+93hgpIfSPARHPA1ejUbnneLPgI6lVxWrwtCjmxV6seCNEh+UofQm7TyE/GXC2e534TrYhhzVbRHpvbSyOyY8MHCePRWX8EdnXtmmT72ZO3AcJE1AdaqYumyVKVZMWSKzdLkplyygjlBXBw/Pvb+71srArtrCg9Yl+svRSDjlHIiCfZYR3oL2Kb+P8a3vROiInxyqAuw8WdfYH/dhGwFfuQwg8kBm7ckYYMZ6WBGJy8wqSjlx2an5456ixGX6Rs/5vlGNYFwBxJh+jAdFKHDW5PEU3KWnknIm6dnL+IOHw5yZzFxYdp2oorY0wTf6dRlTtbHpNAALipnWA/gr3eb6+7qOj1Ayx85hXMsJWIcrCcCJJus3se2+VGlKOLF6tT8J846+K1LoMX/Rfoqc5DMR38yqJKABwDi4ktASUIzZ0GhIH3hcBqYYsEpqtr4DdxqEULM1QZ+AtzcNhfIXOMOb0BmlzmReFrdFmColaB0MJ5Gz9XWkYy1j8Lf2cIt+XzPHhyOvM1t4PF2g4zACWIwt2qD3mqlbk5UcH0xckhBena9Q9Yuqkk5oN1szDv3XjocREfdXwaomcMO8wi1Px23o6KgnQrT54lCzwnvpzCJWNaK5aqbA5xE=
  bucket: logos.svef.is
  skip_cleanup: true
  local-dir: dist
  acl: public-read
  cache_control: "no-cache"
  on:
    branch: master
    repo: svef/logos.svef.is
